version: '3.8'

services:
  buckeyes:
    container_name: rmm
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres
    hostname: rmm
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-init:/var/lib/postgresql
      - ./postgres-data:/var/lib/postgresql/data
      