version: '3.8'

services:
  buckeyes:
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres
    hostname: rmm
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql
      