version: '3.8'

services:
  buckeyes:
    container_name: rmm-db
    networks:
      - rmm
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres
    hostname: rmm-db
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-dump:/var/lib/postgresql
      - ./postgres-init:/docker-entrypoint-initdb.d

networks: 
  rmm:      
      