create sequence rmm_order_number_supply_seq start 100000;
create sequence rmm_order_number_transfer_seq start 100000;
create sequence rmm_product_key_seq start 10000000;

create table rmm_inventory_report ( 
        rmm_inventory_report_id SERIAL NOT NULL, 
        rmm_shop_id                           INTEGER NOT NULL, 
        ir_shop_number                        CHARACTER VARYING(500), 
        ir_status                             CHARACTER VARYING(100), 
        ir_diamonds_category                  CHARACTER VARYING(200), 
        ir_diamonds_cost                      NUMERIC, 
        ir_diamonds_count                     INTEGER, 
        ir_lcd_diamonds_category              CHARACTER VARYING(200), 
        ir_lcd_diamonds_cost                  NUMERIC, 
        ir_lcd_diamonds_count                 INTEGER, 
        ir_asst_dia_bags_category             CHARACTER VARYING(200), 
        ir_asst_dia_bags_cost                 NUMERIC, 
        ir_asst_dia_bags_count                INTEGER, 
        ir_genuine_colored_category           CHARACTER VARYING(200), 
        ir_genuine_colored_cost               NUMERIC, 
        ir_genuine_colored_count              INTEGER, 
        ir_created_colored_category           CHARACTER VARYING(200), 
        ir_created_colored_cost               NUMERIC, 
        ir_created_colored_count              INTEGER, 
        ir_synthetic_colored_category         CHARACTER VARYING(200), 
        ir_synthetic_colored_cost             NUMERIC, 
        ir_synthetic_colored_count            INTEGER, 
        ir_pearls_category                    CHARACTER VARYING(200), 
        ir_pearls_cost                        NUMERIC, 
        ir_pearls_count                       INTEGER, 
        ir_gold_stock_10k_category            CHARACTER VARYING(200), 
        ir_gold_stock_10k_cost                NUMERIC, 
        ir_gold_stock_10k_count               NUMERIC, 
        ir_gold_stock_10k_dwt                 NUMERIC, 
        ir_gold_stock_14k_category            CHARACTER VARYING(200), 
        ir_gold_stock_14k_cost                NUMERIC, 
        ir_gold_stock_14k_count               NUMERIC, 
        ir_gold_stock_14k_dwt                 NUMERIC, 
        ir_gold_stock_18k_category            CHARACTER VARYING(200), 
        ir_gold_stock_18k_cost                NUMERIC, 
        ir_gold_stock_18k_count               NUMERIC, 
        ir_gold_stock_18k_dwt                 NUMERIC, 
        ir_gold_solder_10k_category           CHARACTER VARYING(200), 
        ir_gold_solder_10k_cost               NUMERIC, 
        ir_gold_solder_10k_count              NUMERIC, 
        ir_gold_solder_10k_dwt                NUMERIC, 
        ir_gold_solder_14k_category           CHARACTER VARYING(200), 
        ir_gold_solder_14k_cost               NUMERIC, 
        ir_gold_solder_14k_count              NUMERIC, 
        ir_gold_solder_14k_dwt                NUMERIC, 
        ir_gold_solder_18k_category           CHARACTER VARYING(200), 
        ir_gold_solder_18k_cost               NUMERIC, 
        ir_gold_solder_18k_count              NUMERIC, 
        ir_gold_solder_18k_dwt                NUMERIC, 
        ir_gold_casting_grain_10k_category    CHARACTER VARYING(200), 
        ir_gold_casting_grain_10k_cost        NUMERIC, 
        ir_gold_casting_grain_10k_count       NUMERIC, 
        ir_gold_casting_grain_10k_dwt         NUMERIC, 
        ir_gold_casting_grain_14k_category    CHARACTER VARYING(200), 
        ir_gold_casting_grain_14k_cost        NUMERIC, 
        ir_gold_casting_grain_14k_count       NUMERIC, 
        ir_gold_casting_grain_14k_dwt         NUMERIC, 
        ir_gold_casting_grain_18k_category    CHARACTER VARYING(200), 
        ir_gold_casting_grain_18k_cost        NUMERIC, 
        ir_gold_casting_grain_18k_count       NUMERIC, 
        ir_gold_casting_grain_18k_dwt         NUMERIC, 
        ir_platinum_stock_category            CHARACTER VARYING(200), 
        ir_platinum_stock_cost                NUMERIC, 
        ir_platinum_stock_count               NUMERIC, 
        ir_platinum_stock_dwt                 NUMERIC, 
        ir_platinum_solder_category           CHARACTER VARYING(200), 
        ir_platinum_solder_cost               NUMERIC, 
        ir_platinum_solder_count              NUMERIC, 
        ir_platinum_solder_dwt                NUMERIC, 
        ir_gold_findings_category             CHARACTER VARYING(200), 
        ir_gold_findings_cost                 NUMERIC, 
        ir_gold_findings_count                NUMERIC, 
        ir_gold_findings_dwt                  NUMERIC, 
        ir_platinum_findings_category         CHARACTER VARYING(200), 
        ir_platinum_findings_cost             NUMERIC, 
        ir_platinum_findings_count            NUMERIC, 
        ir_platinum_findings_dwt              NUMERIC, 
        ir_silver_stock_category              CHARACTER VARYING(200), 
        ir_silver_stock_cost                  NUMERIC, 
        ir_silver_stock_count                 NUMERIC, 
        ir_silver_stock_dwt                   NUMERIC, 
        ir_silver_solder_category             CHARACTER VARYING(200), 
        ir_silver_solder_cost                 NUMERIC, 
        ir_silver_solder_count                NUMERIC, 
        ir_silver_solder_dwt                  NUMERIC, 
        ir_silver_casting_grain_category      CHARACTER VARYING(200), 
        ir_silver_casting_grain_cost          NUMERIC, 
        ir_silver_casting_grain_count         NUMERIC, 
        ir_silver_casting_grain_dwt           NUMERIC, 
        ir_silver_findings_category           CHARACTER VARYING(200), 
        ir_silver_findings_cost               NUMERIC, 
        ir_silver_findings_count              NUMERIC, 
        ir_silver_findings_dwt                NUMERIC, 
        ir_total                              NUMERIC, 
        ir_finalized_by                       CHARACTER VARYING(500), 
        ir_finalized_date                     DATE, 
        ir_completion_date                    DATE, 
        ir_shop_approval_status               CHARACTER(1), 
        ir_dm_approval_status                 CHARACTER(1), 
        ir_op_approval_status                 CHARACTER(1), 
        ir_run_date                           DATE, 
        ir_variance_total                     NUMERIC, 
        ir_reviewer1                          CHARACTER VARYING(500), 
        ir_reviewer2                          CHARACTER VARYING(500), 
        ir_month                              CHARACTER VARYING(100), 
        ir_year                               INTEGER, 
        ir_inv_total                          NUMERIC, 
        ir_previous_total                     NUMERIC, 
        ir_add_user_id                        CHARACTER VARYING(500), 
        ir_add_date                           DATE, 
        ir_mtc_user_id                        CHARACTER VARYING(500), 
        ir_mtc_date                           TIMESTAMP(6) WITHOUT TIME ZONE, 
        ir_notes                              CHARACTER VARYING(4000), 
        ir_diamonds_total_value               NUMERIC, 
        ir_lcd_diamonds_total_value           NUMERIC, 
        ir_asst_dia_bags_total_value          NUMERIC, 
        ir_genuine_colored_total_value        NUMERIC, 
        ir_created_colored_total_value        NUMERIC, 
        ir_synthetic_colored_total_value      NUMERIC, 
        ir_pearls_total_value                 NUMERIC, 
        ir_gold_stock_10k_total_value         NUMERIC, 
        ir_gold_stock_14k_total_value         NUMERIC, 
        ir_gold_stock_18k_total_value         NUMERIC, 
        ir_gold_solder_10k_total_value        NUMERIC, 
        ir_gold_solder_14k_total_value        NUMERIC, 
        ir_gold_solder_18k_total_value        NUMERIC, 
        ir_gold_casting_grain_10k_total_value NUMERIC, 
        ir_gold_casting_grain_14k_total_value NUMERIC, 
        ir_gold_casting_grain_18k_total_value NUMERIC, 
        ir_platinum_stock_total_value         NUMERIC, 
        ir_platinum_solder_total_value        NUMERIC, 
        ir_gold_findings_total_value          NUMERIC, 
        ir_platinum_findings_total_value      NUMERIC, 
        ir_silver_stock_total_value           NUMERIC, 
        ir_silver_solder_total_value          NUMERIC, 
        ir_silver_casting_grain_total_value   NUMERIC, 
        ir_silver_findings_total_value        NUMERIC, 
        ir_asst_dia_bags_dwt                  NUMERIC, 
        PRIMARY KEY (rmm_inventory_report_id) 
    );

create table "rmm_supply_categories" (
  "rmm_supply_categories_id" SERIAL PRIMARY KEY not null,
  "sc_category" varchar(200),
  "sc_description" varchar(1000),
  "sc_bulk_item" char(1),
  "sc_add_user_id" varchar(500),
  "sc_add_date" date,
  "sc_mtc_user_id" varchar(500),
  "sc_mtc_date" date,
  "sc_type" varchar(200),
  "sc_supply_type" varchar(500)
);

create table "rmm_product" (
  "rmm_product_id" SERIAL PRIMARY KEY not null,
  "rmm_supply_categories_id" SERIAL REFERENCES rmm_supply_categories("rmm_supply_categories_id"),
  "p_key" varchar(1000),
  "p_type" varchar(100),
  "p_description" varchar(4000),
  "p_cost" decimal,
  "p_status" varchar(100),
  "p_name" varchar(1000),
  "p_quality" varchar(100),
  "p_cut" varchar(100),
  "p_shape" varchar(100),
  "p_color" varchar(100),
  "p_ster_quality" varchar(100),
  "p_add_user_id" varchar(500),
  "p_add_date" date,
  "p_mtc_user_id" varchar(500),
  "p_mtc_date" date,
  "p_size" varchar(200),
  "p_size_mm" varchar(200),
  "p_size_ct" varchar(200),
  "p_sku" varchar(1000),
  "p_quantity" integer,
  "p_is_gemstone" char(1)
);

create table "rmm_product_sku" (
  "rmm_product_sku_id" SERIAL PRIMARY KEY not null,
  "rmm_product_id" SERIAL REFERENCES rmm_product("rmm_product_id"),
  "ps_sku" varchar(500),
  "ps_status" varchar(100),
  "ps_add_user_id" varchar(500),
  "ps_add_date" date,
  "ps_mtc_user_id" varchar(500),
  "ps_mtc_date" date
);

create table "rmm_order" (
  "rmm_order_id" SERIAL PRIMARY KEY not null,
  "rmm_user_id" varchar(500),
  "rmm_shop_id" SERIAL,
  "rmm_vendor_id" SERIAL,
  "o_number" varchar(100),
  "o_type" varchar(100),
  "o_date" date,
  "o_status" varchar(100),
  "o_store_comment" varchar(4000),
  "o_message" varchar(4000),
  "o_is_received" char(1),
  "o_is_delivered" char(1),
  "o_is_custom" char(1),
  "o_repair_job_num" varchar(500),
  "o_series" varchar(12),
  "o_approved_by" varchar(500),
  "o_approved_by_date" date,
  "o_add_user_id" varchar(500),
  "o_add_date" date,
  "o_mtc_user_id" varchar(500),
  "o_mtc_date" date,
  "o_error_msg" varchar(4000),
  "o_error" char(1),
  "o_vendor_name" varchar(500),
  "o_shop_number" varchar(100),
  "o_from_shop_number" varchar(100),
  "o_to_shop_number" varchar(100),
  "o_transfer_status" varchar(200),
  "o_request_status" varchar(200),
  "o_ordered_status" varchar(200)
);

create table "rmm_order_line_item" (
  "rmm_order_line_item_id" SERIAL PRIMARY KEY not null,
  "rmm_order_id" SERIAL REFERENCES rmm_order("rmm_order_id"),
  "rmm_product_id" SERIAL REFERENCES rmm_product("rmm_product_id"),
  "oli_product_key" varchar(1000),
  "oli_description" varchar(4000),
  "oli_message" varchar(4000),
  "oli_uom" varchar(100),
  "oli_line_num" decimal,
  "oli_quantity_ordered" decimal,
  "oli_quantity_delivered" decimal,
  "oli_quantity_invoiced" decimal,
  "oli_add_user_id" varchar(500),
  "oli_add_date" date,
  "oli_mtc_user_id" varchar(500),
  "oli_mtc_date" date,
  "oli_error_msg" varchar(1000),
  "oli_job_numbers" varchar(1000),
  "oli_status" varchar(100)
);

CREATE TABLE rmm_order_line_item_return ( 
    "rmm_order_line_item_return_id" SERIAL PRIMARY KEY NOT NULL, 
    "rmm_order_line_item_id" SERIAL REFERENCES rmm_order_line_item("rmm_order_line_item_id"), 
    "olir_quantity"          NUMERIC, 
    "olir_uom"               CHARACTER VARYING(50), 
    "olir_reason"            CHARACTER VARYING(1000), 
    "olir_add_user_id"       CHARACTER VARYING(500), 
    "olir_add_date"          TIMESTAMP(6) WITHOUT TIME ZONE, 
    "olir_mtc_user_id"       CHARACTER VARYING(500), 
    "olir_mtc_date"          TIMESTAMP(6) WITHOUT TIME ZONE
);

create table "rmm_invoice" (
  "rmm_invoice_id" SERIAL PRIMARY KEY not null,
  "rmm_order_id" SERIAL REFERENCES rmm_order("rmm_order_id"),
  "i_number" varchar(200),
  "i_status" varchar(200),
  "i_date" date,
  "i_grand_total" decimal,
  "i_sent_to_sap" char(1),
  "i_sent_to_sap_date" date,
  "i_sent_to_sap_batch_num" varchar(200),
  "i_pay_to_sap" char(1),
  "i_original_grand_total" numeric,
  "i_original_currency" varchar(30),
  "i_add_user_id" varchar(500),
  "i_add_date" date,
  "i_mtc_user_id" varchar(500),
  "i_mtc_date" date
);

create table "rmm_invoice_line_item" (
  "rmm_invoice_line_item_id" SERIAL PRIMARY KEY not null,
  "rmm_invoice_id" SERIAL REFERENCES rmm_invoice("rmm_invoice_id"),
  "rmm_order_line_item_id" SERIAL REFERENCES rmm_order_line_item("rmm_order_line_item_id"),
  "rmm_product_id" SERIAL REFERENCES rmm_product("rmm_product_id"),
  "ili_description" varchar(2000),
  "ili_line_num" decimal,
  "ili_cost" decimal,
  "ili_quantity" decimal,
  "ili_tax_amount" decimal,
  "ili_total_amount" decimal,
  "ili_original_amount" numeric,
  "ili_original_currency" varchar(30),
  "ili_add_user_id" varchar(500),
  "ili_add_date" date,
  "ili_mtc_user_id" varchar(500),
  "ili_mtc_date" date
);

create table "rmm_shop_inventory" (
  "rmm_shop_inventory_id" SERIAL PRIMARY KEY not null,
  "rmm_shop_id" integer,
  "si_shop_number" varchar(500),
  "si_status" varchar(100),
  "si_total_value" decimal,
  "si_notes" varchar(4000),
  "si_add_user_id" varchar(500),
  "si_add_date" date,
  "si_mtc_user_id" varchar(500),
  "si_mtc_date" date
);

create table "rmm_shop_inventory_product" (
  "rmm_product_id" integer REFERENCES rmm_product("rmm_product_id") not null,
  "rmm_shop_inventory_id" integer REFERENCES rmm_shop_inventory("rmm_shop_inventory_id"),
  "sip_count" decimal,
  "sip_status" varchar(100),
  "sip_total_value" decimal,
  "sip_add_user_id" varchar(500),
  "sip_add_date" date,
  "sip_mtc_user_id" varchar(500),
  "sip_mtc_date" date,
  PRIMARY KEY(rmm_product_id, rmm_shop_inventory_id)
);

create table "rmm_shop_inventory_product_jobnum" (
  "rmm_product_id" integer REFERENCES rmm_product("rmm_product_id") not null,
  "rmm_shop_inventory_id" integer REFERENCES rmm_shop_inventory("rmm_shop_inventory_id"),
  "sipj_job_number" varchar(1000),
  "sipj_status" varchar(100),
  "sipj_add_user_id" varchar(500),
  "sipj_add_date" date,
  "sipj_mtc_user_id" varchar(500),
  "sipj_mtc_date" date,
  PRIMARY KEY(rmm_product_id, rmm_shop_inventory_id, sipj_job_number)
);

create table "rmm_metal_rates" (
  "rmm_metal_rate_id" SERIAL not null,
  "mr_metal_type" varchar(500),
  "mr_metal_name" varchar(500),
  "mr_rate" decimal,
  "mr_status" varchar(100),
  "mr_add_user_id" varchar(500),
  "mr_add_date" date,
  "mr_mtc_user_id" varchar(500),
  "mr_mtc_date" date,
  "mr_category" varchar(200),
  "rmm_supply_category_id" integer
);

create table "rmm_types" (
  "rmm_type_id" SERIAL PRIMARY KEY not null,
  "pt_type_category" varchar(200),
  "pt_type_code" varchar(200),
  "pt_type_name" varchar(500),
  "pt_sequence_num" integer,
  "pt_add_user_id" varchar(500),
  "pt_add_date" date,
  "pt_mtc_user_id" varchar(500),
  "pt_mtc_date" date
);

create table "rmm_types_apps" (
  "rmm_type_id" integer REFERENCES rmm_types("rmm_type_id") not null,
  "ta_app" varchar(100),
  "ta_add_user_id" varchar(500),
  "ta_add_date" date,
  "ta_mtc_user_id" varchar(500),
  "ta_mtc_date" date,
  PRIMARY KEY(rmm_type_id, ta_app)
);

create table "rmm_types_xref" (
  "rmm_type_parent_id" integer REFERENCES rmm_types("rmm_type_id") not null,
  "rmm_type_child_id" integer REFERENCES rmm_types("rmm_type_id") not null,
  "tx_type_status" varchar(500),
  "tx_add_user_id" varchar(500),
  "tx_add_date" date,
  "tx_mtc_user_id" varchar(500),
  "tx_mtc_date" date,
  PRIMARY KEY(rmm_type_parent_id, rmm_type_child_id)
);

create table "rmm_batch_etl" (
  "rmm_batch_etl_id" SERIAL PRIMARY KEY not null,
  "be_status" varchar(100),
  "be_date" timestamp,
  "be_comment" varchar(4000),
  "be_add_user_id" varchar(500),
  "be_add_date" timestamp,
  "be_mtc_user_id" varchar(500),
  "be_mtc_date" timestamp
);

create table "rmm_currency_exchange" (
  "rmm_currency_exchange_id" SERIAL PRIMARY KEY not null,
  "ce_from_currency" varchar(30),
  "ce_to_currency" varchar(30),
  "ce_exchange_date" timestamp,
  "ce_exchange_rate" numeric,
  "ce_add_user_id" varchar(500),
  "ce_add_date" timestamp,
  "ce_mtc_user_id" varchar(500),
  "ce_mtc_date" timestamp
);

CREATE TABLE rmm_order_vendor_file (
    "rmm_order_vendor_file_id" SERIAL PRIMARY KEY NOT NULL,
    "rmm_order_line_item_id" integer REFERENCES rmm_order_line_item("rmm_order_line_item_id") not null,
    "ovf_filename" VARCHAR(1000),
    "ovf_po_no" VARCHAR(100),
    "ovf_line_no" VARCHAR(100),
    "ovf_vendor" VARCHAR(100),
    "ovf_shop" VARCHAR(100),
    "ovf_po_date" VARCHAR(100),
    "ovf_vendor_no" VARCHAR(100),
    "ovf_desc" VARCHAR(4000),
    "ovf_ext_desc" VARCHAR(4000),
    "ovf_qty" VARCHAR(100),
    "ovf_uom" VARCHAR(100),
    "ovf_category" VARCHAR(100),
    "ovf_order_no" VARCHAR(100),
    "ovf_sku" VARCHAR(100),
    "ovf_size" VARCHAR(100),
    "ovf_series" VARCHAR(100),
    "ovf_quality" VARCHAR(100),
    "ovf_size_ct" VARCHAR(100),
    "ovf_size_mm" VARCHAR(100),
    "ovf_type" VARCHAR(100),
    "ovf_shape" VARCHAR(100),
    "ovf_color" VARCHAR(100),
    "ovf_cut" VARCHAR(100),
    "ovf_unique" VARCHAR(100),
    "ovf_length" VARCHAR(100),
    "ovf_flow" VARCHAR(100),
    "ovf_surface_finish" VARCHAR(100),
    "ovf_uom2" VARCHAR(100),
    "ovf_description2" VARCHAR(4000),
    "ovf_gauge" VARCHAR(100),
    "ovf_finished_state" VARCHAR(100),
    "ovf_series_description" VARCHAR(4000),
    "ovf_alloy" VARCHAR(100),
    "ovf_dimension" VARCHAR(100),
    "ovf_add_user_id" varchar(500),
    "ovf_add_date" timestamp,
    "ovf_mtc_user_id" varchar(500),
    "ovf_mtc_date" timestamp
);

CREATE TABLE rmm_invoice_vendor_file (
    "rmm_invoice_vendor_file_id" SERIAL PRIMARY KEY NOT NULL,
    "rmm_invoice_line_item_id" integer REFERENCES rmm_invoice_line_item("rmm_invoice_line_item_id") not null,
    "ivf_filename" VARCHAR(1000),
    "ivf_vendor_name" VARCHAR(100),
    "ivf_vendor_no" VARCHAR(100),
    "ivf_vendor" VARCHAR(100),
    "ivf_po_no" VARCHAR(100),
    "ivf_line_no" VARCHAR(100),
    "ivf_shop" VARCHAR(100),
    "ivf_ship_date" VARCHAR(100),
    "ivf_ship_dt" VARCHAR(100),
    "ivf_po_date" VARCHAR(100),
    "ivf_amount" VARCHAR(100),
    "ivf_description" VARCHAR(4000),
    "ivf_desc" VARCHAR(4000),
    "ivf_ext_desc" VARCHAR(4000),
    "ivf_qty" VARCHAR(100),
    "ivf_uom" VARCHAR(100),
    "ivf_category" VARCHAR(100),
    "ivf_invoice_no" VARCHAR(100),
    "ivf_unit_cost" VARCHAR(100),
    "ivf_sku" VARCHAR(100),
    "ivf_product_key" VARCHAR(100),
    "ivf_size" VARCHAR(100),
    "ivf_series" VARCHAR(100),
    "ivf_quality" VARCHAR(100),
    "ivf_size_ct" VARCHAR(100),
    "ivf_size_mm" VARCHAR(100),
    "ivf_type" VARCHAR(100),
    "ivf_shape" VARCHAR(100),
    "ivf_color" VARCHAR(100),
    "ivf_cut" VARCHAR(100),
    "ivf_unique" VARCHAR(100),
    "ivf_length" VARCHAR(100),
    "ivf_flow" VARCHAR(100),
    "ivf_surface_finish" VARCHAR(100),
    "ivf_uom2" VARCHAR(100),
    "ivf_description2" VARCHAR(4000),
    "ivf_gauge" VARCHAR(100),
    "ivf_finished_state" VARCHAR(100),
    "ivf_series_description" VARCHAR(4000),
    "ivf_alloy" VARCHAR(100),
    "ivf_dimension" VARCHAR(100),
    "ivf_gold_price" VARCHAR(100),
    "ivf_silver_price" VARCHAR(100),
    "ivf_srsp_compliance" VARCHAR(100),
    "ivf_wdc_sow_compliance" VARCHAR(100),
    "ivf_invoice_currency" VARCHAR(100),
    "ivf_add_user_id" varchar(500),
    "ivf_add_date" timestamp,
    "ivf_mtc_user_id" varchar(500),
    "ivf_mtc_date" timestamp
);
